# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMapSuggest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gf_id', models.CharField(db_index=True, max_length=20)),
                ('supp_id', models.CharField(db_index=True, max_length=20)),
                ('gf_name', models.CharField(max_length=255)),
                ('supp_name', models.CharField(max_length=255)),
                ('name_score', models.IntegerField()),
                ('gf_address', models.CharField(max_length=255)),
                ('supp_address', models.CharField(max_length=255)),
                ('address_score', models.IntegerField()),
                ('gf_city', models.CharField(max_length=255)),
                ('supp_city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'HotelMapSuggest',
            },
        ),
    ]
