# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmapsuggest',
            name='supplier',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='address_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='gf_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='gf_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='gf_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='name_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='supp_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='supp_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='supp_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
