# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20171025_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='gf_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
