# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20171025_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmapsuggest',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
